<?php
//$lang[''] = '';
$lang['license'] = 'License Information';
$lang['info'] = 'Information';
$lang['stat'] = 'Statistics';
$lang['bindip'] = 'Bind to IP';
$lang['is'] = 'Information about the software';
$lang['os'] = 'Operating System';
$lang['vwebserv'] = 'Web Server version';
$lang['vphp'] = 'PHP version';
$lang['vzo'] = 'Zend Optimizer version';
$lang['ni'] = 'Not installed';
$lang['timeos'] = 'OS run-time';
$lang['vioncube'] = 'IonCube Loader version';
$lang['vsmarty'] = 'Smarty version';
$lang['vgeoip'] = 'GeoIP Country version';
$lang['ea'] = 'Information about eAccelerator';
$lang['veacc'] = 'eAccelerator version';
$lang['rame'] = 'Memory (total / free / used)';
$lang['cachescr'] = 'Cached scripts';
$lang['vermysql'] = 'MySQL version';
$lang['timemysql'] = 'MySQL run-time';
$lang['ct'] = 'Number of tables';
$lang['sdb'] = 'Total size of the database';
$lang['im'] = 'Information about MySQL';
$lang['modules'] = 'Modules';
$lang['uo'] = 'Users online';
$lang['login'] = 'Login';
$lang['ip'] = 'IP';
$lang['lasta'] = 'Last activity';
$lang['dab'] = 'Delete all bots';
$lang['dap'] = 'Delete all processes';
$lang['dzrp'] = 'Delete q./r. of search';
$lang['cadb'] = 'Clear the entire database';
$lang['sb'] = 'Statistic of bots';
$lang['ba'] = 'Total bots';
$lang['bvn'] = 'Total new bots';
$lang['bva'] = 'Total active bots';
$lang['bz24'] = 'Bots in 24 hours';
$lang['bz7'] = 'Bots in 7 days';
$lang['bz1'] = 'Bots in 1 month';
$lang['sodb'] = 'Database size (bots info)';
$lang['sp'] = 'Statistics of the processes';
$lang['sa'] = 'Total processes';
$lang['spo'] = 'Search statistic';
$lang['az'] = 'Total queries / results';
$lang['sdbzp'] = 'Database size (queries / results)';
$lang['sc'] = 'Countries statistic';
$lang['ac'] = 'Total countries';
$lang['rdb'] = 'Database size';
$lang['et'] = 'End of trial period';
$lang['cher'] = 'after';
$lang['ram'] = 'Memory (total / available)';
$lang['swap'] = 'Swap (total / available)';
$lang['hdd'] = 'HDD (total / available)';
$lang['loados'] = 'OS load (in 1/5/15 minutes)';
$lang['system'] = 'System (user / system / iowait / idle)';
$lang['day'] = array('0' => 'days', '1' => 'day', '2' => 'days', '3' => 'days', '4' => 'days', '5' => 'days', '6' => 'days', '7' => 'days', '8' => 'days', '9' => 'days', '11' => 'days', '12' => 'days', '13' => 'days', '14' => 'days');
$lang['hour'] = array('0' => 'hours', '1' => 'hour', '2' => 'hours', '3' => 'hours', '4' => 'hours', '5' => 'hours', '6' => 'hours', '7' => 'hours', '8' => 'hours', '9' => 'hours', '11' => 'hours', '12' => 'hours', '13' => 'hours', '14' => 'hours');
$lang['min'] = array('0' => 'minutes', '1' => 'minute', '2' => 'minutes', '3' => 'minutes', '4' => 'minutes', '5' => 'minutes', '6' => 'minutes', '7' => 'minutes', '8' => 'minutes', '9' => 'minutes', '11' => 'minutes', '12' => 'minutes', '13' => 'minutes', '14' => 'minutes');
$lang['sec'] = array('0' => 'seconds', '1' => 'second', '2' => 'seconds', '3' => 'seconds', '4' => 'seconds', '5' => 'seconds', '6' => 'seconds', '7' => 'seconds', '8' => 'seconds', '9' => 'seconds', '11' => 'seconds', '12' => 'seconds', '13' => 'seconds', '14' => 'seconds');


?>
