#!/bin/sh

if [ -z $BW ]; then
  export BW=4
fi

if [ -z $2 ]; then
  exit 1
fi

case $1 in
  -s|set)
    [ -n $3] && export $2=$3
    ;;
  -u|unset)
    export $2=
    ;;
  *)
    usage
    exit 1
    ;;
esac
