#!/usr/bin/env ruby
# coding: utf-8

CL = "\e[0m"
BO = "\e[1m"

Z = "\e[30m"
R = "\e[31m" 
G = "\e[32m"
Y = "\e[33m"
B = "\e[34m"
P = "\e[35m"
C = "\e[36m"
W = "\e[37m"

print <<EOF 
 
  #{BO}#{Z}██#{CL}  #{BO}#{R}██#{CL}  #{BO}#{G}██#{CL}  #{BO}#{Y}██#{CL}  #{BO}#{B}██#{CL}  #{BO}#{P}██#{CL}  #{BO}#{C}██#{CL}  #{BO}#{W}██#{CL}
  #{BO}#{Z}██#{CL}  #{BO}#{R}██#{CL}  #{BO}#{G}██#{CL}  #{BO}#{Y}██#{CL}  #{BO}#{B}██#{CL}  #{BO}#{P}██#{CL}  #{BO}#{C}██#{CL}  #{BO}#{W}██#{CL}
  #{Z}██#{CL}  #{R}██#{CL}  #{G}██#{CL}  #{Y}██#{CL}  #{B}██#{CL}  #{P}██#{CL}  #{C}██#{CL}  #{W}██#{CL}
  #{Z}██#{CL}  #{R}██#{CL}  #{G}██#{CL}  #{Y}██#{CL}  #{B}██#{CL}  #{P}██#{CL}  #{C}██#{CL}  #{W}██#{CL}
 
EOF
