GRANT ALL PRIVILEGES ON *.* TO bcserver@"%" IDENTIFIED BY '1q2w3eQAZ' WITH GRANT OPTION;
CREATE DATABASE bcserver_db;
USE bcserver_db;
CREATE TABLE clients (CreateTime DATETIME, AccessTime DATETIME, ServerPort SMALLINT UNSIGNED, ClientPort SMALLINT UNSIGNED, Address INT UNSIGNED, Flags INT UNSIGNED, UserId CHAR(128), CountryCode CHAR(2), AddressStr CHAR(16), LoadPct INT UNSIGNED);
