SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `bf_none` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `host` varchar(64) NOT NULL,
  `data` blob NOT NULL,
  `type` tinyint(11) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `log` (`host`,`type`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=54606 ;

CREATE TABLE IF NOT EXISTS `bf_unnecessary` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `host` varchar(64) NOT NULL,
  `data` blob NOT NULL,
  `type` tinyint(11) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `log` (`host`,`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
